### ISSUE TITLE
looks like this plugin can not decode the request text

### ISSUE THREAD

**Issue by songyang666** [BlueMatthew/ProtobufInspector#1]

**Comment by BlueMatthew** [comment]
No, decoding on request data has not been implemented yet as I did not get such requirement... It is easy to add. It is better if you can provide the data format you are using, for example,  the header that indicates message type of protobuf data, or descriptor set.

**Comment by BlueMatthew** [comment]
I checked Charles and it uses the same rule for response and request data. I will make it like Charles.

**Comment by BlueMatthew** [comment]
Fixed in v1.2
